version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: "simapp"
    ports:
      - "8080:8080"
  
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: "reactapp"
    ports:
      - "443:3000"
    depends_on:
      - backend