version: '3'

services:
  backend:
    env_file:
        "./.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "simapp"
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "reactapp"
    ports:
      - "3000:3000"
    links:
      - "backend:be"
